"""
Django settings for mrds project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# print("This is bd="+str(BASE_DIR))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(h71z^+(d44urv&70-i(4^s6(^_85s@al==7&chf(xep6@-g)q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web_app',
    'rest_framework',
    'corsheaders',
    'django_extensions',
    'admin_app',
    'refer_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mrds.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mrds.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'mrds_v1',
        'USER': 'postgres',
        'PASSWORD': 'ms',
        'HOST': 'mrdsv1.cpu2ck2283sh.eu-north-1.rds.amazonaws.com',
        'PORT': 5432
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    }
]


SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_SECURE = True
# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS =(
    os.path.join(BASE_DIR, 'templates/static'),
)

# TODO: Remove all print statements
print(STATICFILES_DIRS)
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ORIGIN_ALLOW_ALL = True

SMS = {
    'apiurl': "https://api.textlocal.in/send/?",
    'apikey': "NzI3NzRlNDI3NDM5NzU1NTc5Njc3NzM4NTY0MzZmNGU=",
    'sender': 600010
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'testemail.co.in@gmail.com'
EMAIL_HOST_PASSWORD = 'xfcyblbkdvqylsnf'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# TODO: These elements must be shifted to a static file
OTP_SUBJECT_TEMPLATE = "OTP to login/signup MRDS"
OTP_SMS_TEMPLATE = "Dear user, please use #OTP# to login/signup our application. - MRDS Team"
OTP_EMAIL_TEMPLATE = "Dear user, please use #OTP# to login/signup our application.\n Thanks,\n MRDS Team"
REFERRAL_SUBJECT_TEMPLATE = "You have been referred"
REFERRAL_SMS_TEMPLATE = "Dear user, please use #CODE# to login/signup our application. - MRDS Team"
REFERRAL_EMAIL_TEMPLATE_SIGNUP = "<html><body>Dear #PATIENT_NAME#,<br>Dr. #DR_NAME# has referred you. please <a href='#REFER_LINK#'>click below link </a> to register yourself in our application " \
"<br><a href='#REFER_LINK#'>#REFER_LINK#<a><br> Thanks,<br> MRDS Team</body></html>"
REFERRAL_EMAIL_TEMPLATE_LOGIN = "<html><body>Dear #PATIENT_NAME#,<br>Dr. #DR_NAME# has referred you. please <a href='#REFER_LINK#'>click below link </a> to login in our application " \
"<br><a href='#REFER_LINK#'>#REFER_LINK#<a><br> Thanks,<br> MRDS Team</body></html>"
