# Generated by Django 3.2 on 2024-07-01 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_name', models.CharField(max_length=50)),
                ('coupon_code', models.CharField(max_length=20)),
                ('coupon_description', models.CharField(max_length=200)),
                ('coupon_value', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('coupon_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('coupon_modified_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
    ]
