# Generated by Django 3.2 on 2024-07-01 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refer_Patient',
            fields=[
                ('refer_patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('diagnosis', models.CharField(max_length=50)),
                ('treatment', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('referred_by', models.IntegerField()),
                ('referred_to', models.IntegerField()),
                ('referral_code', models.CharField(max_length=50)),
                ('referred_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'refer_patient',
            },
        ),
    ]
