# Generated by Django 4.2 on 2024-07-11 13:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileName', models.CharField(max_length=50)),
                ('profile_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('qualification_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('user_type_id', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'qualification',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('user_type_id', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'specialization',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_name', models.CharField(max_length=100)),
                ('subscription_details', models.CharField(max_length=255)),
                ('subscription_validity', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('user_type_id', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_mobile', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=10)),
                ('profile_image_name', models.CharField(max_length=50, null=True)),
                ('user_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('user_type_id', models.SmallIntegerField()),
                ('referral_code', models.CharField(default=None, max_length=10, null=True)),
            ],
            options={
                'db_table': 'mrds_user',
            },
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('user_package_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('package_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user_package',
            },
        ),
        migrations.CreateModel(
            name='UserPatientRefer',
            fields=[
                ('user_patient_refer_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_appointment_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('user_from', models.IntegerField()),
                ('user_to', models.IntegerField()),
                ('refer_notes', models.CharField(max_length=200)),
                ('refer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_patient_refer',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_type',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('user_subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_id', models.IntegerField()),
                ('subscription_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscription_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.user')),
            ],
            options={
                'db_table': 'user_subscription',
            },
        ),
        migrations.CreateModel(
            name='UserSpecialization',
            fields=[
                ('user_specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization_id', models.IntegerField()),
                ('documents', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.user')),
            ],
            options={
                'db_table': 'user_specialization',
            },
        ),
        migrations.CreateModel(
            name='UserQualification',
            fields=[
                ('user_qualification_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification_id', models.IntegerField()),
                ('documents', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.user')),
            ],
            options={
                'db_table': 'user_qualification',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('about_me', models.TextField(blank=True)),
                ('total_experience', models.IntegerField(default=0)),
                ('consultation_fees', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.user')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('user_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_id', models.IntegerField()),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_mode', models.CharField(max_length=50)),
                ('payment_amount', models.CharField(max_length=101)),
                ('payment_status', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('txn_id', models.CharField(max_length=50)),
                ('coupon_code', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.user')),
            ],
            options={
                'db_table': 'user_payment',
            },
        ),
        migrations.CreateModel(
            name='UserConsultation',
            fields=[
                ('user_consult_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_consult_by', models.IntegerField()),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('user_referred_to', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.user')),
            ],
            options={
                'db_table': 'user_consultation',
            },
        ),
        migrations.CreateModel(
            name='UserClinicAvailibility',
            fields=[
                ('User_Clinic_Availibility', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.user')),
            ],
            options={
                'db_table': 'user_clinic_availibility',
            },
        ),
        migrations.CreateModel(
            name='UserClinic',
            fields=[
                ('user_clinic_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_id', models.IntegerField()),
                ('consultation_fees', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.user')),
            ],
            options={
                'db_table': 'user_clinic',
            },
        ),
        migrations.CreateModel(
            name='UserAppointment',
            fields=[
                ('user_appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('user_clinic_id', models.CharField(max_length=50)),
                ('appointment_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment_type', models.CharField(max_length=50)),
                ('appointment_status', models.IntegerField(default=1)),
                ('payment_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.user')),
            ],
            options={
                'db_table': 'user_appointment',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('user_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('dist', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('address_type', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.user')),
            ],
            options={
                'db_table': 'user_address',
            },
        ),
    ]
