# Generated by Django 3.2 on 2024-07-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='mrds_user',
        ),
    ]
