# Generated by Django 3.2 on 2024-07-04 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'default_related_name': 'package'},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'default_related_name': 'qualification'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'default_related_name': 'specialization'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'default_related_name': 'subscription'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_related_name': 'mrds_user'},
        ),
        migrations.AlterModelOptions(
            name='user_address',
            options={'default_related_name': 'user_address'},
        ),
        migrations.AlterModelOptions(
            name='user_package',
            options={'default_related_name': 'user_package'},
        ),
        migrations.AlterModelOptions(
            name='user_profile',
            options={'default_related_name': 'user_profile'},
        ),
        migrations.AlterModelOptions(
            name='user_qualification',
            options={'default_related_name': 'user_qualification'},
        ),
        migrations.AlterModelOptions(
            name='user_specialization',
            options={'default_related_name': 'user_specialization'},
        ),
        migrations.AlterField(
            model_name='user_address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_address', to='web_app.user'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='web_app.user'),
        ),
        migrations.AlterField(
            model_name='user_qualification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_qualification', to='web_app.user'),
        ),
        migrations.AlterField(
            model_name='user_specialization',
            name='specialization_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_specialization',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_specialization', to='web_app.user'),
        ),
    ]
