# Generated by Django 3.2 on 2024-07-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20240704_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_qualification',
            name='qualification_id',
            field=models.IntegerField(),
        ),
    ]
